// Code generated by hertz generator.

package url_shorten

import (
	"context"

	"url_shorten/biz/handler"
	url_shorten "url_shorten/biz/model/url_shorten"
	"url_shorten/consts"
	"url_shorten/service"

	"github.com/cloudwego/hertz/pkg/app"
)

// CreateShortUrl .
// @router /api/ceate [POST]
func CreateShortURL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req url_shorten.CreateShortUrlReq
	baseHandler := &handler.BaseHandler{}
	err = c.BindAndValidate(&req)
	if err != nil {
		baseHandler.ErrorResponse(ctx, c, &consts.ParamError, nil)
		return
	}

	resp, bizCode := service.CreateShortURL(ctx, &req)
	if bizCode != nil {
		baseHandler.ErrorResponse(ctx, c, bizCode, nil)
		return
	}
	baseHandler.SuccessResponse(c, resp)
}

// Query .
// @router /:code [GET]
func Query(ctx context.Context, c *app.RequestContext) {
	var err error
	var req url_shorten.QueryReq
	baseHandler := &handler.BaseHandler{}
	err = c.BindAndValidate(&req)
	if err != nil {
		baseHandler.ErrorResponse(ctx, c, &consts.ParamError, nil)
		return
	}

	shortURL, bizCode := service.Query(ctx, &req)
	if bizCode != nil {
		baseHandler.ErrorResponse(ctx, c, bizCode, nil)
		return
	}
	c.Redirect(302, []byte(shortURL.OriginURL))
}
